### ISSUE TITLE
Bug perde itens

### ISSUE THREAD

**Issue by realtino** [Ars3ne/aEventos#7]
Quando fiz o evento semáforo no meu servidor ele nao devolveu os itens do player mas deixou o backup salvo , acho que deveria ter um comando de backup caso aconteça isso , estou usando a versão 1.16.5 com mods

Creio que o erro foi esse
[aEventos] Plugin aEventos v1.5.1 generated an exception while executing task 12434
java.util.NoSuchElementException: null
        at java.util.LinkedList.removeFirst(Unknown Source) ~[?:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:184) ~[json-simple-1.1.1.jar:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[json-simple-1.1.1.jar:?]
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[json-simple-1.1.1.jar:?]
        at com.ars3ne.eventos.manager.ConnectionManager.lambda$addParticipation$5(ConnectionManager.java:392) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:90) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[forge:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:20) ~[forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Ars3ne** [comment]
Tente usar essa versão do plugin para ver se o problema foi resolvido: https://cdn.discordapp.com/attachments/738584177473093755/1162936897555923045/aEventos-1.5.1.jar?ex=653dc062&is=652b4b62&hm=25ebfac8563881151b8aba3b90c73e83cc5bdd86b119273704599f8e7980ddf3&
O log que você me enviou não possui nenhuma relação com esse problema e pode ser ignorado.

**Comment by realtino** [comment]
Eu ja estou usando a versao 1.5.1, vou testar dnv o erro e ver se aparece no painel

**Comment by realtino** [comment]
https://youtu.be/qZZUPdtl1kc , bom eu testei novamente e continua perdendo os itens e nao aparece nenhuma mensagem de erro

**Comment by Ars3ne** [comment]
Voce esta usando especificamente a JAR que eu te enviei? Pois apesar de eu não ter mudado o nome do arquivo, ela possui melhorias e correções adicionais se comparada com a versao 1.5.1 disponível publicamente que possui esses problemas. Caso não esteja usando ela, então voce continuara perdendo os itens.

**Comment by realtino** [comment]
de madrugada eu testo essa jar , pensei que era a mesma

**Comment by realtino** [comment]
Acabei de testar novamente e continua perdendo os itens

**Comment by Ars3ne** [comment]
Eu acabei de testar o evento semáforo e eu estou recebendo os itens de volta normalmente ao ser eliminado. Eu irei perguntar novamente: você está usando especificamente a JAR que eu te enviei? Você está usando mods no seu servidor? Qual tipo de software você está usando no seu servidor? Ele é híbrido?

**Comment by realtino** [comment]
Estou usando modpack do atm 6 to the sky , e usando mohist no servidor e tbm baixei essa jar que vc mandou acima

**Comment by Ars3ne** [comment]
O aEventos não da suporte a servidores híbridos como o Mohist devido ao fato destes mudarem alguns aspectos importantes no funcionamento do Bukkit, o que acaba causando erros que eu não posso corrigir ou reproduzir. Os únicos softwares suportados sao o Paper e suas forks diretas (Purpur, Pufferfish, etc.)
